my_project/urls.py
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include 

from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
    path('register/', user_views.register, name="user-register"),
     # new urls
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name="user-login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="user-logout"),
    path('profile/', user_views.profile, name="user-profile"),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='users/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name="recipe-home"),
    
    path('recettes/', views.recipes_view, name="recettes-recipe"),
    path('recettesadmin/', views.admin_recipe , name="recettes-recipe-admin"),
    path('recettesutilisateur/', views.admin_recipe , name="recettes-recipe-utilisateur"),
    
    path('recettes/<int:pk>', views.RecipeDetailView.as_view(), name="recettes-detail"),
    path('recettes/create', views.RecipeCreateView.as_view(), name="recettes-create"),
    #path('recipe/<int:pk>/update', views.RecipeUpdateView.as_view(), name="recettes-update"),
    path('recipe/<int:pk>/update', views.update_recipe2, name="recettes-update"),
    path('recipe/<int:pk>/delete', views.RecipeDeleteView.as_view(), name="recettes-delete"),
    
    #path('ingredients/', views.IngredientListView.as_view(), name="ingredients-recipe"),
    path('ingredients/', views.Ingredient_view , name="ingredients-recipe"),
    path('ingredients/<int:pk>', views.IngredientDetailView.as_view(), name="ingredients-detail"),
    path('ingredients/create', views.IngredientCreateView.as_view(), name="ingredients-create"),
    path('ingredients/<int:pk>/update', views.IngredientUpdateView.as_view(), name="ingredients-update"),
    path('ingredients/<int:pk>/delete', views.IngredientDeleteView.as_view(), name="ingredients-delete"),
    
    
    path('familles/', views.Famille_view, name="familles-recipe"),
    path('familles/<int:pk>', views.FamilleDetailView.as_view(), name="familles-detail"),
    path('familles/create', views.FamilleCreateView.as_view(), name="familles-create"),
    path('familles/<int:pk>/update', views.FamilleUpdateView.as_view(), name="familles-update"),
    path('familles/<int:pk>/delete', views.FamilleDeleteView.as_view(), name="familles-delete"),
    path('familles-ingredients/<int:pk>', views.Famille_ingredients, name="famille-ingredients"),
    
    path('ingredients/', views.ingredients, name="ingredients-recipe"),
    path('familles/', views.familles, name="familles-recipe"),

    path('create/', views.create_recipe2, name="create_recipe"),
    path('create_process/<int:pk>', views.create_process, name="create_recipe_process"),
    path('update_process/<int:pk>', views.update_process, name="update_recipe_process"),


    path('recipe/testCascade', views.ingredient_create_view, name="test_cascade"),

    #path('pdf/<int:pk>', views.GeneratePdf.as_view(), name="pdf_recipe"),
    path('pdf/<int:pk>', views.generatePdf, name="pdf_recipe"),

    path('ajax/load-ingredients/', views.load_ingredient, name='ajax_load_ingredient'),
    path('ajax/load-formes/', views.load_forme, name='ajax_load_forme'),
]

recipe/models.py
from shutil import _ntuple_diskusage
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

#from my_project.recipe.views import ingredients


# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length=500)
    #description = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    #prep_time = models.DurationField()
    #cook_time = models.DurationField()
    #servings = models.IntegerField()


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("recettes-detail", kwargs={"pk": self.pk})
    
     
    
class Famille(models.Model):
    
#    name = models.CharField(max_length=100,   unique=True)
    name = models.CharField(max_length=1000)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("familles-detail", kwargs={"pk": self.pk})

class Forme(models.Model):
    name = models.CharField(max_length=500)
    famille = models.ForeignKey(Famille, on_delete=models.CASCADE, related_name="forme_famille", null=True)
    def __str__(self):
        return self.name
    
    #def get_absolute_url(self):
        #return reverse("familles-detail", kwargs={"pk": self.pk})
    
class Ingredient(models.Model):
    famille = models.ForeignKey(Famille, on_delete=models.CASCADE, related_name="famille_ingredient", null=True)
    forme = models.ForeignKey(Forme, on_delete=models.CASCADE, related_name="forme_ingredient", null=True, verbose_name='ingrédient')
    name = models.CharField(max_length=500, verbose_name='forme')
    energie_kJ = models.FloatField(null= True)
    energie_kcal = models.FloatField(null= True)
    sodium = models.FloatField(null= True)
    glucide = models.FloatField(null= True)
    proteins = models.FloatField(null= True)
    
    fibres = models.FloatField(null= True)
    eau = models.FloatField(null= True)
    lipide = models.FloatField(null= True)
    sucres = models.FloatField(null= True)
    fructose = models.FloatField(null= True)
    galactose = models.FloatField(null= True)
    glucose = models.FloatField(null= True)
    lactose = models.FloatField(null= True)
    maltose = models.FloatField(null= True)
    saccharose = models.FloatField(null= True)
    amidon = models.FloatField(null= True)

    fibresALimentraires = models.FloatField(null= True)
    polyols = models.FloatField(null= True)
    cendres = models.FloatField(null= True)
    alcool = models.FloatField(null= True)

    acidesOrganiques = models.FloatField(null= True)
    AGsatures = models.FloatField(null= True)
    AGmonoinsature = models.FloatField(null= True)
    AGpolyinsature = models.FloatField(null= True)
    AGbutyrique = models.FloatField(null= True)
    AGcaproique = models.FloatField(null= True)
    AGcaprylique = models.FloatField(null= True)
    AGcaprique = models.FloatField(null= True)
    AGlaurique = models.FloatField(null= True)
    AGmyristique = models.FloatField(null= True)
    AGpalmitique = models.FloatField(null= True)
    AGbstearique = models.FloatField(null= True)
    AGoleique = models.FloatField(null= True)
    AGlinoleique = models.FloatField(null= True)
    AGalphalinolenique = models.FloatField(null= True)

    AGarachidonique = models.FloatField(null= True)
    AGepa = models.FloatField(null= True)
    AGdha = models.FloatField(null = True)

    cholesterol = models.FloatField(null= True)
    selchlorure = models.FloatField(null= True)
    calcium = models.FloatField(null= True)
    chlorure = models.FloatField(null= True)
    cuivre = models.FloatField(null= True)
    fer = models.FloatField(null= True)
    iode = models.FloatField(null= True)
    magnesium = models.FloatField(null= True)
    manganese = models.FloatField(null= True)
    phosphore = models.FloatField(null= True)
    potassium = models.FloatField(null= True)
    selenium = models.FloatField(null= True)
    zinc = models.FloatField(null= True)

    retinol = models.FloatField(null= True)
    betaCarotene = models.FloatField(null= True)

    vitamineD = models.FloatField(null= True)
    vitamineE = models.FloatField(null= True)
    VitamineK1 = models.FloatField(null= True)
    vitamineK2 = models.FloatField(null= True)
    vitamineB1 = models.FloatField(null= True)
    vitamineB2 = models.FloatField(null= True)
    VitamineB3 = models.FloatField(null= True)
    vitamineB5 = models.FloatField(null= True)
    vitamineB6 = models.FloatField(null= True)
    vitamineB9 = models.FloatField(null= True)

    #to chaine into vitamine minuscule
    VitamineB12 = models.FloatField(null= True)



    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("ingredients-detail", kwargs={"pk": self.pk})
    
class Contraintes(models.Model):
    famille_1 = models.ForeignKey(Famille, on_delete=models.CASCADE)
    seuil = models.FloatField()
    
class IngredientRecipe(models.Model): 
    famille = models.ForeignKey(Famille, on_delete=models.CASCADE, related_name="ingredients_recipe_famille", null=True)
    forme = models.ForeignKey(Forme, on_delete=models.CASCADE, related_name="ingredients_recipe_forme", null=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ingredients_recipe")
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name="xyz", null=True)
    #ingredient = models.CharField(max_length=100)
    quantity = models.FloatField(null=True)
    
    
    def __str__(self):  
        return self.ingredient.name

class ProcessRecipe(models.Model): 
    step = models.CharField(max_length=100)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="process_recipe")

    #ingredient = models.CharField(max_length=100)
    
    
    def __str__(self):  
        return self.recipe.title


class CookingRecipe(models.Model): 
    step = models.CharField(max_length=100)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="cooking_recipe")

    #ingredient = models.CharField(max_length=100)
    
    
    def __str__(self):  
        return self.recipe.title


class FamilleTest(models.Model):
    name = models.CharField(max_length=100)
       
    def __str__(self):  
        return self.name        

class IngredientTest(models.Model):
    name = models.CharField(max_length=100)
    famille = models.ForeignKey(FamilleTest, on_delete=models.CASCADE, related_name="famille_ingredient")  
    energie_kJ = models.FloatField(null= True)

    def __str__(self):  
        return self.name




'''    
class ContraintesRecipe(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient_recette = models.ForeignKey(IngredientRecipe, on_delete=models.CASCADE)
    contraintes_recette = models.ForeignKey(Contraintes, on_delete=models.CASCADE)
    
    
    def __str__(self):  
        return self.name'''

recipe/forms.py
from django import forms
from .models import Famille, Forme, Ingredient, IngredientRecipe, Recipe, ProcessRecipe, CookingRecipe

class RecipeForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = 'Titre'

    class Meta :
        model = Recipe
        fields = '__all__' 
        exclude = ('author',)


    def clean_servings(self):
        value = self.cleaned_data.get("servings")
        print(value)
        if value < 1:
            raise forms.ValidationError("The number of servings must be greater than zero.")
        return value
        
class IngredientForm(forms.ModelForm):

    class Meta:
        model = IngredientRecipe
        exclude = ('recipe',)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['forme'].label = 'ingredient'
        self.fields['name'].label = 'forme'




    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        #self.fields['ingredient'].queryset = Ingredient.objects.all().order_by('name')
        self.fields['ingredient'].queryset = Ingredient.objects.all()
        self.fields['famille'].queryset = Famille.objects.all()
        self.fields['forme'].queryset = Forme.objects.all()

        #print(self.data)
        
        #if 'ingredient' in self.data:
        #    try:
        #        famille_id1 = int(self.data.get('famille'))
        #        self.fields['ingredient'].queryset = Ingredient.objects.filter(pk =famille_id1).order_by('name')
        #    except (ValueError, TypeError):
        #        pass  # invalid input from the client; ignore and fallback to empty City queryset
        #elif self.instance.pk:
        #    self.fields['ingredient'].queryset = self.instance.famille.famille_ingredient.order_by('name')

IngredientFormSet = forms.inlineformset_factory(Recipe, IngredientRecipe, form=IngredientForm, extra=0)

class ProcessForm(forms.ModelForm):
    step = forms.CharField(widget=forms.Textarea)
    #short_desc = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = ProcessRecipe
        exclude = ('recipe',)

    def __init__(self, *args, **kwargs):
        super(ProcessForm, self).__init__(*args, **kwargs) # Call to ModelForm constructor
        self.fields['step'].widget.attrs['style'] = 'width:80%; height:40px;'
        #self.fields['long_desc'].widget.attrs['style']  = 'width:800px; height:80px;'

class CookingForm(forms.ModelForm):
    step = forms.CharField(widget=forms.Textarea)
    #short_desc = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = CookingRecipe
        exclude = ('recipe',)

    def __init__(self, *args, **kwargs):
        super(CookingForm, self).__init__(*args, **kwargs) # Call to ModelForm constructor
        self.fields['step'].widget.attrs['style'] = 'width:80%; height:40px;'
        #self.fields['long_desc'].widget.attrs['style']  = 'width:800px; height:80px;'


ProcessFormSet = forms.inlineformset_factory(Recipe, ProcessRecipe, form=ProcessForm, extra=0)
CookingFormSet = forms.inlineformset_factory(Recipe, CookingRecipe, form=CookingForm, extra=0)


Formset_Params = {
    'form-TOTAL_FORMS' : '100',
    'form-INITIAL_FORMS' : '1',
    'form-MIN_NUM_FORMS' : '1', 
}    

users/views.py
# users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from . import forms

# Create your views here.
def register(request):
  if request.method == "POST":
    form = forms.UserRegisterForm(request.POST)
    if form.is_valid():
      form.save()
      # cleaned data is a dictionary
      username = form.cleaned_data.get('username')
      messages.success(request, f"{username}, you're account is created!")
      return redirect('user-login')
  else:
    form = forms.UserRegisterForm()
  return render(request, 'users/register.html', {'form': form})

@login_required()
def profile(request):
  return render(request, 'users/profile.html')

recipe/templates/recipe/create_recipe.html
{% extends 'recipe/base.html' %}

{%block back%} 
{%url "recipe-home" %}
{%endblock back%}



{% block content%}
{%load crispy_forms_tags%}

<!-- 

<div class="container">
    <div class="row">
        <div class="col">
        <h1> Add a Recipe </h1>
        <form action = "." method="post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <br>
            {{ formset.management_form}}
            {% for form in formset %}
            {{form|crispy}}
            {% endfor %}          
            <button type="submit">Submit </button>
        </form>
        </div>
    </div>
</div>


-->


<h3> Ajouter les ingrédients :</h3>

<form id="pet_form"  action="."  method="post" enctype="multipart/form-data">

    {% csrf_token %}

    {{ form|crispy }}


</br>
</br>
</br>
    {{ formset.management_form }}
    {% for form in formset %}
    <div class="image-form d-flex justify-content-between"  id="recipeForm" data-formes-url="{% url 'ajax_load_forme' %}"  data-ingredients-url="{% url 'ajax_load_ingredient' %}"  >
            
        <div class = "row">
            <br>
            <br>

            <div class = " col-sm">
                Famille :
                {{ form.famille}}
            </div>

            <div class = " col-sm">
                Ingrédient :
                {{ form.forme}}
            </div>  

            <div class = " col-sm">
                Forme :
                {{ form.ingredient}}
            </div>  

            <div class = " col-sm">
                Quantité (g):
                {{ form.quantity}}
            </div>  


                {{form.DELETE}}

            <div class = " col-sm">
                <br>
                <button class="align-self-center btn btn-danger delete-image-form">supprimer</button>
            </div>

        </div>

    </div>    

    {% endfor %}


    <input type="submit" value="Passer au processus de preparation" name='terminerBttn'/>  </button>
    <button id="add-image-form" class="btn btn-primary my-3">ajouter un nouvel ingrédient</button>
    <input type="hidden" name="counter_newid" value="3" id="id_counter_new_id">
</form>



<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>


<script>

const imageForm = document.getElementsByClassName("image-form");
const mainForm = document.querySelector("#pet_form");
const addImageFormBtn = document.querySelector("#add-image-form");
const submitFormBtn = document.querySelector('[type="submit"]');
const totalForms = document.getElementById("id_ingredients_recipe-TOTAL_FORMS");

const counterID = document.getElementById("id_counter_new_id");

function updateForms() {
    let formCount = imageForm.length ;
    let count = 0;
    for (let form of imageForm) {
        const formRegex = RegExp(`ingredients_recipe-(\\d){1}-`, 'g');
        form.innerHTML = form.innerHTML.replace(formRegex, `ingredients_recipe-${count++}-`)
    }
}

addImageFormBtn.addEventListener("click", function (event) {
    event.preventDefault();
    //let formCount = imageForm.length ;
    const formCount = imageForm.length
    //const formCount = parseInt(counterID.getAttribute('value')) + 1 ;
    var newImageForm = imageForm[0].cloneNode(true);
    const formRegex = RegExp(`ingredients_recipe-(\\d){1}-`, 'g');

    newImageForm.innerHTML = newImageForm.innerHTML.replace(formRegex, `ingredients_recipe-${formCount}-`);

        
    newImageForm.style.visibility = 'visible';
    newImageForm.style.height='100%';

    mainForm.insertBefore(newImageForm, submitFormBtn);
    totalForms.setAttribute('value', formCount + 1);

    //counterID.setAttribute('value', formCount + 1);

    get_ingredients();
});

mainForm.addEventListener("click", function (event) {
    let formCount = imageForm.length ;
    if (event.target.classList.contains("delete-image-form")) {
        event.preventDefault();
        const deleteRegex = RegExp(`id_ingredients_recipe-(\\d){1}-DELETE-`, 'g');
        event.target.parentElement.parentElement.parentElement.querySelectorAll('[id$="-DELETE"]')[0].checked = true;
        //console.log(event.target.parentElement.querySelectorAll('[id$="-DELETE"]')[0].checked)
        //console.log(document.querySelectorAll('[id$="-DELETE"]'))
        console.log('Test')
        
        //event.target.parentElement.remove();
        event.target.parentElement.parentElement.parentElement.style.visibility = 'hidden';
        event.target.parentElement.parentElement.parentElement.style.height=0;
        // show - use this for inline elements (span, a)
        //formCount--;
        //updateForms();
        //totalForms.setAttribute('value', 5);
    }
});
</script>


<!-- 
<h1>Add a new bird</h1>
<form id="form-container" method="POST">
    {% csrf_token %}
    {{bird_formset.management_form}}
    {% for form in bird_formset %}
    <div class="bird-form">
    {{form.as_p}}
    </div>
    {% endfor %}
    <button id="add-form" type="button">Add Another Bird</button>
    <button type="submit">Create Birds</button>
</form>


<script>
    let birdForm = document.querySelectorAll(".bird-form")
    let container = document.querySelector("#form-container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

    let formNum = birdForm.length-1
    addButton.addEventListener('click', addForm)

    function addForm(e){
        e.preventDefault()

        let newForm = birdForm[0].cloneNode(true)
        let formRegex = RegExp(`ingredients_recipe-(\\d){1}-`,'g')

        formNum++
        newForm.innerHTML = newForm.innerHTML.replace(formRegex, `ingredients_recipe-${formNum}-`)
        container.insertBefore(newForm, addButton)
        
        totalForms.setAttribute('value', `${formNum+1}`)
    }
</script>
-->

<script>
    var del = document.querySelectorAll('[id$="-DELETE"]')

    for (let i=0; i < del.length; i++ ) {
        console.log(del[i]);
        del[i].style.visibility = 'hidden';
    }
        
</script>

<script>
 
    //for (let i = 0; i < imageForm.length; i++) {
    const id_count = $("id_counter_new_id")
    
    function get_ingredients() {

        for (let i = 0; i < 10; i++) { 
            //console.log(i)
        const formRegex1 = '#' + 'id_ingredients_recipe-'+ i + '-famille'
        const formRegex2 = '#' + 'id_ingredients_recipe-' + i + '-forme'
        console.log(formRegex1)
        const id1 = $(formRegex1)
        const id2 = $(formRegex2)
        id1.change(function () {
            const url = $("#recipeForm").attr("data-formes-url");  // get the url of the `load_cities` view
            const familleId = $(this).val();  // get the selected country ID from the HTML input

            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'famille_id': familleId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $(id2).html(data); 
                     // replace the contents of the city input with the data that came from the server
                    /*

                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (city) {
                        html_data += `<option value="${city.id}">${city.name}</option>`
                    });
                    console.log(html_data);
                    $("#id_city").html(html_data);

                    */
                }
            });


        });

        }




        for (let i = 0; i < 10; i++) {
            console.log(i)
            const formRegex1 = '#' + 'id_ingredients_recipe-'+ i + '-forme'
            const formRegex2 = '#' + 'id_ingredients_recipe-' + i + '-ingredient'
            const id1 = $(formRegex1)
            const id2 = $(formRegex2)
            id1.change(function () {
                console.log("Test Change ingredient");
                const url = $("#recipeForm").attr("data-ingredients-url");  // get the url of the `load_cities` view
                const formeId = $(this).val();  // get the selected country ID from the HTML input

                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'forme_id': formeId       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        $(id2).html(data);  // replace the contents of the city input with the data that came from the server
                    /*

                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (city) {
                        html_data += `<option value="${city.id}">${city.name}</option>`
                    });
                    console.log(html_data);
                    $("#id_city").html(html_data);

                    */
                    console.log(data);
                }
            });

        });

        }




    }

    get_ingredients()



</script>
{% endblock %}

recipe/templates/recipe/familles.html
{% extends 'recipe/base.html' %}


    {% block content %}
    <h1> Mes familles d'ingrédients </h1>
    {% for famille in familles%}

    <div class="card" style="width: 18rem;">
  
        <div class="card-body">
            <h5 class="card-title"> {{famille.name}} </h5>
            {% for ingredient in ingredients%}
                {% if ingredient.famille == famille%}
                    <p class="card-text">{{ingredient}}</p>
                {% endif %}
            {% endfor %}
            <a href="#" class="card-link">voir détails ingrédient</a>
        </div>
    </div>
    
    {%endfor%}
    {% endblock content%}

recipe/templates/recipe/recipe_confirm_delete.html
# recipes/templates/recipes/recipe_confirm_delete.html
{% extends "recipe/base.html" %}
<!-- -->
{% load crispy_forms_tags %}
<!-- -->

{%block back%} 
{%url "recettes-recipe" %}
{%endblock back%}



{% block content %}
<div class="container">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="mb-4">Voulez-vous vraiment supprimer cette recette?</legend>
      <h2>{{object}}</h2>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group py-3">
      <input class="btn btn-outline-danger" type="submit" value="Delete" />
    </div>
  </form>
  <div class="border-top pt-3">
    <a class="text-muted" href="{% url 'recettes-recipe' %}"
      >Cancel</a
    >
  </div>
</div>

<!-- -->
{% endblock content %}

recipe/templates/recipe/recipe_form.html
{% extends "recipe/base.html" %}
<!-- -->
{% load crispy_forms_tags %}
<!-- -->

{%block back%} 
{%url "recipe-home" %}
{%endblock back%}


{% block content %}
<div class="container">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Create Recipe</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group py-3">
      <input class="btn btn-outline-primary" type="submit" value="Save" />
    </div>
  </form>
  <div class="border-top pt-3">
    <a class="text-muted" href="{% url 'recettes-recipe' %}">cancel</a>
  </div>
</div>

<!-- -->
{% endblock content %}

recipe/templates/recipe/test_cascade.html
{% extends 'recipe/base.html' %}


    {% block content %}

    <form method="post" id="recipeForm" data-ingredient-url="{% url 'ajax_load_ingredient' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script>
        $("#id_famille").change(function () {
            console.log("Test Change");
            const url = $("#recipeForm").attr("data-ingredient-url");  // get the url of the `load_cities` view
            const familleId = $(this).val();  // get the selected country ID from the HTML input
    
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                data: {
                    'famille_id': familleId       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_ingredient").html(data);  // replace the contents of the city input with the data that came from the server
                    /*
    
                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (city) {
                        html_data += `<option value="${city.id}">${city.name}</option>`
                    });
                    console.log(html_data);
                    $("#id_city").html(html_data);
    
                    */
                }
            });
    
        });
    </script>
    {% endblock content%}